# theme:
#   name: material
# site_name: Dester Docs
site_name: Dester Docs

theme:
    name: "material"
    palette:
      - scheme: default
        primary: cyan
        accent: indigo
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - scheme: slate
        primary: cyan
        accent: indigo
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
    favicon: assets/favicon.ico
    icon:
        repo: fontawesome/brands/github
    logo: assets/logo-dark-small.svg
    font: false
    custom_dir: docs
    features:
    - navigation.instant
    - navigation.tracking
    # - navigation.tabs
    - navigation.indexes

    - search.suggest
    - search.share
nav:
  - What's Dester:
    - index.md
  - Getting Started:
    - getting-started\prerequisite-setup.md
    - getting-started\local-deployement.md
    - getting-started\heroku-deployment.md
    - getting-started\desktop-application.md
  - Building:
    - building\frontend.md
    - building\backend.md
    - building\desktop.md
  - About:
    - additional-info\main.md
    - additional-info\privacy-policy.md
    - additional-info\terms-and-conditions.md

repo_name: "DesterLib/Dester"
repo_url: "https://github.com/DesterLib/Dester"

markdown_extensions:
    - markdown.extensions.admonition
    - markdown.extensions.codehilite:
          guess_lang: false
    - markdown.extensions.meta

plugins:
    - search
    - git-authors
    - minify:
          minify_html: true
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/DesterLib

    - icon: fontawesome/brands/telegram 
      link: https://telegram.dog/s/Dester_Community

    - icon: fontawesome/solid/arrow-pointer 
      link: https://demo.dester.gq

copyright: Copyright &copy; 2021 - 2022 Dester Team